### ISSUE TITLE
A change of the ghard factor is not applied

### ISSUE THREAD

**Issue by pustelbaer** [smarthausleben/ioBroker.wamo#19]
If you change the ghard factor in the adapter instance settings, the value is not applied. Even though the instance is restarted, the value in the object tree stays at 0.030303.

There seems to be an issue with the decimal seperator as well. By default the UI shows a comma, but when you enter a new value with  decimal it changes to a dot. Entering the value with dot instead of comma does not solve the issue. 

BTW, with the default ghard factor the adapter shows me a ghardness of over 50. My real ghardness is about 28.

**Comment by smarthausleben** [comment]
Change of the calculation factor in instance settings will be reflected immediately after adapter restart. So the calculation factor in settings is always used for calculation of **German Water Hardness** but corresponding object is updated only in very long timer method and therefore it takes a while until the new value will be shown in the object. => I will add the readout and actualization for this object into the instance startup process in order to have the correct value in the object right after start of the instance. => Change will be implemented into next release.

Regarding the “decimal separator” issue, there is nothing I can do because this depends on your global ioBroker settings and maybe as well on the country / region settings of your device running ioBroker.

Regarding accuracy of German Water Hardness calculation, you may have a look at the closed Issue #16 (but it’s written in German language) where this topic was already discussed in more detail.

Pleas let me know if I can close this Issue.

**Comment by smarthausleben** [comment]
ghard factor object will be updated during startup : release v0.2.13
