### ISSUE TITLE
Installation needed manual work - dependency on tough-cookie

### ISSUE THREAD

**Issue by woessmich** [smarthausleben/ioBroker.wamo#2]
Installation did only work after I manually installed “tough-cookie”.
This should happen without command line interaction.

Also the adapter seems not to be correctly registered in the iobroker repository. It needs to be installed with the full link to Github, as it seems not even in the dev repository.

**Comment by smarthausleben** [comment]
I can't find anything related to “tough-cookie” within my repository. So I have no idea why you needed to do manual installation. But this doesn’t mean you are not right about this. It just means I can’t find anything I can fix.

You are right, the adapter is not part of the official adapters list. To be honest, the procedure to get the adapter into the official adapter list is not really well documented. There is one or maybe two YT-videos and some crumbs in forums. Same applies to the whole documentation related to adapter development at all. For example:  Till today I unfortunately wasn’t even able (maybe because I’m to stupid) to get substantial information about Admin 5 conform adapter development.

**Comment by smarthausleben** [comment]
WAMO adapter is now available in the official adapter list of ioBroker. For the moment the adapter is listed in **Beta (latest)** only.
