### ISSUE TITLE
Adapter does not Show up under instances

### ISSUE THREAD

**Issue by kris1989132** [smarthausleben/ioBroker.wamo#22]
Adapter does irregularly install But does Not Show up under instances.

**Comment by smarthausleben** [comment]
What exactly means “irregularly install”?

**Comment by weindler** [comment]
> I Said the adapter:
> 
> 1: sometimes installed sometimes didn’t install 2: if installed it was not visible in the instances section

Hi, ja das ist normal daß der Adapter nicht in den Instanzen zu finden ist, du mußt ihn hinzufügen, mit dem Plus Zeichen, da github beta adapter nicht automatisch eine Instanz im iobroker erzeugen.

Hi, yes it's normal that the adapter isn't found in the instances, you have to add it with the plus sign, because github beta adapter doesn't automatically create an instance in iobroker.

**Comment by kris1989132** [comment]
Neither adapter nor instances show up - so no setting, no objects. But adapter is installed if I check in console/ssh…

**Comment by kris1989132** [comment]
Added instance manually… worked out! Thx!

**Comment by smarthausleben** [comment]
I’m glad it works now 😊

But, to be honest, I have no idea what went wrong on your ioBroker system. This adapter is running on many ioBroker systems without any problems.

Just a thought:
In order to install the adapter from the ioBroker “Adapter” page you need to enable “Beta (latest)” in your ioBroker settings in Tab Repositories.
If you don’t enable “Beta (latest)” the Adapter will not show up in the adapter list because there is no “stable version” yet.
Manual Installation directly from Github (using the “Kat”) is not really a good idea, because this version is changing frequently and may not work at all.

**Comment by smarthausleben** [comment]
> > I Said the adapter:
> > 1: sometimes installed sometimes didn’t install 2: if installed it was not visible in the instances section
> 
> Hi, ja das ist normal daß der Adapter nicht in den Instanzen zu finden ist, du mußt ihn hinzufügen, mit dem Plus Zeichen, da github beta adapter nicht automatisch eine Instanz im iobroker erzeugen.
> 
> Hi, yes it's normal that the adapter isn't found in the instances, you have to add it with the plus sign, because github beta adapter doesn't automatically create an instance in iobroker.

Correct, the adapter is not showing up in the “Adapter” area if  you didn’t enable “Beta (latest)” in your ioBroker settings in Tab Repositories. 

But once it is installed (NPM, Github or Beta (latest)) it should **definitely show up in the “Instances”** area of ioBroker.

**Comment by weindler** [comment]
ok, wieder was dazu gelernt, wusste ich jetzt auch nicht, wenn man beta nicht in iob einstellt, daß dem dann so ist.

**Comment by weindler** [comment]
nein, beta habe ich auch nicht angehakt, habe es über git installiert.

**Comment by smarthausleben** [comment]
> nein, beta habe ich auch nicht angehakt, habe es über git installiert.

Danke für deine Rückmeldung.

Ich habe übrigens gerade eben den Release **_v0.3.0_** erstellt.
