### ISSUE TITLE
Log-Error: Device is not responding

### ISSUE THREAD

**Issue by swenp76** [smarthausleben/ioBroker.wamo#9]
![Screenshot 2022-07-19 092744](https://user-images.githubusercontent.com/95631202/179692066-909d1fa0-6195-4031-ae4b-11b5c0da522b.png)
**Describe the bug**  
After about 15 min of working fine the instance starts to continuosly log 

2022-07-19 08:54:27.333  - warn: wamo.0 (25319) Warnmeldung
2022-07-19 08:54:27.335  - error: wamo.0 (25319) [async getData(statesToGet)] 1 try / Device at 192.168.99.26:5333is not responding
2022-07-19 08:54:27.335  - warn: wamo.0 (25319) Waiting for 3 seconds ...
2022-07-19 08:54:30.336  - warn: wamo.0 (25319) retry connection ...

In the meantime the values are still read out of the device.

This only stops of the instance is stopped or restarted.

From the code it seems as if each value is read out of the device using a single http-request. 
Maybe using the single
`http://ip-address:5333/safe-tec/get/all`
call parsing the json string could be better. I'm using this in fhem to get all parameters from the device every 5 s successfully for months now without problems.

Adapter version is 0.1.4, running on raspberry 3+

**Comment by smarthausleben** [comment]
http://ip-address:5333/safe-tec/get/all is not really an option because in a further release I would like to make each parameter selectable for read out in the settings page.
So I have to fix the issue related to connection dropouts to the device. Since the read requests to the device are handled within different timers, some of the values will still be updated where other requests are hanging. So I need to improve the whole read request handling.

**Comment by smarthausleben** [comment]
Related to #1

**Comment by smarthausleben** [comment]
fixed in release v0.1.5
